// ============================================================
// Turtle Labs — SINGLE SHARED CONTENT SOURCE
// Home, Works, Journal and the CMS all read from this file.
// Edit here (or via the mock CMS) and every page updates.
// ES module: import { TL_CONTENT } from './tl-content.js'
// ============================================================

export const TL_CONTENT = {

  // ---- WORKS / PORTFOLIO -------------------------------------------------
  // cat drives the Works-page tabs. Keep the first 6 as the homepage set.
  works: [
    { id:'w-95', cat:'video', tag:'Video & Motion', title:'Real Estate - Teaser Ad - 95', initials:'DT', accent:'#FF8A5C', tagBg:'rgba(255,69,0,0.15)', grad:'linear-gradient(135deg,#1F0A05,#33150A)', weeks:'6 weeks', loc:'Dubai, UAE', video:'assets/video/95canal-heights.mp4', thumb:'assets/video/95canal-heights-thumb.png', desc:'A high-impact brand trailer positioning tough industrial equipment for Gulf enterprise buyers - scripted, shot and scored to cut through a spec-sheet market.', outcomes:['2.1M organic views in the launch quarter','+38% lift in inbound enterprise enquiries','Adopted as the opener at 3 Gulf trade expos'] },
    { id:'w-wysax', cat:'identity', tag:'Brand Identity', title:'WYSAX Systems Design', initials:'WY', accent:'#4ADE80', tagBg:'rgba(0,168,107,0.15)', grad:'linear-gradient(135deg,#06180E,#0C2A16)', thumb:'assets/works/wysax-thumb.png', thumbFit:'contain', thumbBg:'#ffffff', weeks:'5 weeks', loc:'Toronto, Canada', video:'', desc:'Complete brand architecture for a B2B enterprise software company entering the North American market - logo system, typography hierarchy, colour grammar and pitch templates.', outcomes:['New brand launched across 12 touchpoints in 6 weeks','Series A pitch deck redesign led to a $2M close','NPS score up 31 points post-rebrand'] },
    { id:'w-ush', cat:'identity', tag:'Brand Identity', title:'USH Naturals Branding', initials:'OW', accent:'#4ADE80', tagBg:'rgba(0,168,107,0.15)', grad:'linear-gradient(135deg,#081A10,#10301C)', thumb:'assets/video/ush-naturals.png', weeks:'4 weeks', loc:'Kochi, India', video:'', desc:"A complete brand identity for a natural foods company - logo system, leaf-mark, typography and packaging-ready guidelines built around the promise of delivering nature's goodness.", outcomes:['Cohesive identity rolled out across pack and web','+52% repeat orders on the D2C store','Stocked by 2 national retail chains'] },
    { id:'w-smw', cat:'identity', tag:'Brand Identity', title:'The SMW Group - Fintech Branding', initials:'SMW', accent:'#EC3013', tagBg:'rgba(236,48,19,0.15)', grad:'linear-gradient(135deg,#000000,#0B0B0C)', weeks:'8 weeks', loc:'London, UK', video:'', thumb:'assets/works/smw-logo-black.jpg', thumbFit:'cover', thumbBg:'#000000',
      desc:'A distinctive, credible and contemporary identity for a fintech business operating in the competitive UK financial-services landscape - balancing financial credibility with a modern, technology-led character that communicates trust, clarity and forward thinking.',
      media:[
        { kind:'image', src:'assets/works/smw-system-design.png', bg:'#f3f2f2', caption:'System design & mockup - brand identity, site architecture and merchant portal screens' },
        { kind:'image', src:'assets/works/smw-email-signature.jpg', bg:'#ffffff', caption:'Email signature template' },
        { kind:'image', src:'assets/works/smw-business-cards.jpg', bg:'#f3f2f2', caption:'Business cards - front and back' }
      ],
      stats:[
        { value:'01', label:'Complete brand identity system' },
        { value:'12', label:'Logo concepts & iterations' },
        { value:'40+', label:'Brand assets developed' },
        { value:'8', label:'Digital touchpoints designed' },
        { value:'6', label:'Communication templates' },
        { value:'8 wks', label:'Strategy to final delivery' }
      ],
      story:[
        { n:'01', head:'The Challenge', body:'SMW Group was entering a crowded UK financial-services market where trust is won or lost in seconds. Its existing presentation looked generic and did not signal the credibility or technology-led ambition of the business, making it hard to stand apart from established players.' },
        { n:'02', head:'The Objective', body:'Reposition SMW from an undifferentiated fintech into a brand that reads as credible, contemporary and unmistakably its own - shifting perception across every customer-facing touchpoint from website to business card.' },
        { n:'03', head:'Strategy', body:'We defined the target audience, mapped the competitive landscape and set a brand personality that pairs financial rigour with a modern, human warmth. Positioning and messaging were built around trust, clarity and forward thinking.' },
        { n:'04', head:'Identity Development', body:'The logo pairs a vivid, multi-colour particle burst with a confident wordmark - order emerging from many moving parts, a fitting metaphor for fintech. We set a colour system, typographic hierarchy and graphic language that hold up in one colour or full spectrum, on black or white.' },
        { n:'05', head:'Digital Application', body:'The identity was translated into web, interface, email and presentation touchpoints - a coherent system rather than isolated designs, tuned for social, sales and day-to-day business communications.' },
        { n:'06', head:'Brand System', body:'Rather than one-off artefacts, we built a scalable system: business cards, email signatures and letterhead share the same grammar, so the brand stays consistent as it grows across formats and teams.' },
        { n:'07', head:'Results', body:'The relaunched identity gave SMW a confident, premium presence and a single visual language across every channel - materially lifting brand recognition and the consistency of stakeholder-facing communications.' },
        { n:'08', head:'Final Impact', body:'The new identity helped SMW Group present itself as a more credible, contemporary and differentiated fintech brand - equipped to compete for attention and trust in the UK financial-services market.' }
      ],
      outcomes:['Complete, scalable identity system across digital and print','Consistent brand grammar on cards, email and letterhead','A credible, contemporary presence built for a UK fintech audience'] },
    { id:'w-malabar', cat:'packaging', tag:'Packaging Design', title:'Malabar Reserve Specialty Pack', initials:'MR', accent:'#FFB35C', tagBg:'rgba(255,140,0,0.15)', grad:'linear-gradient(135deg,#1F1405,#33230A)', weeks:'8 weeks', loc:'Singapore', video:'', desc:'Zero-plastic compostable pouch packaging with an embedded QR origin-tracing story for a specialty coffee exporter.', outcomes:['100% compostable pack, zero plastic','30% of buyers scanned the QR origin story','+19% shelf pickup in retail trials'] },
    { id:'w-ritz', cat:'packaging', tag:'Event Collateral', title:'The Ritz London - Spring \u201926 Collateral', initials:'RZ', accent:'#60A5FA', tagBg:'rgba(0,102,178,0.15)', grad:'linear-gradient(135deg,#0A1428,#132247)', weeks:'4 weeks', loc:'London, UK', video:'', thumb:'assets/video/ritz-logo-thumb.png', thumbFit:'contain', thumbBg:'#ffffff', image:'assets/video/ritz-leaflet.png', media:[{ kind:'image', src:'assets/video/ritz-leaflet.png', caption:'Spring \u201926 events leaflet — full spread' },{ kind:'image', src:'assets/video/ritz-logo-thumb.png', fit:'contain', bg:'#ffffff', caption:'Heritage wordmark used across the collateral' }], desc:'A seasonal event leaflet for The Ritz London - a full spread announcing the Spring \u201926 programme, from the Bollinger La Grande Ann\u00e9e launch to the Caviar & Champagne Experience, set in the hotel\u2019s house typographic style.', outcomes:['Two-page leaflet spanning the full Spring \u201926 events calendar','Typeset in the hotel\u2019s heritage brand style','Print-ready collateral for in-house and guest distribution'] },
    { id:'w-iucn', cat:'video', tag:'Event Film', title:'IUCN - Leaders Forum Highlights', initials:'MT', accent:'#67E8F9', tagBg:'rgba(0,163,224,0.15)', grad:'linear-gradient(135deg,#051318,#0A2630)', thumb:'assets/video/iucn-leaders-forum-thumb.png', weeks:'3 weeks', loc:'Geneva, Switzerland', video:'assets/video/iucn-leaders-forum.mp4', desc:'Event coverage of the IUCN Leaders Forum - headlined by Ban Ki-moon - cut into an impactful highlights film that asks the hard questions and inspires action.', outcomes:['Distilled a full-day forum into a sharp highlights film','Framed around questions that provoke and inspire action','Amplified the Forum\'s message to a global audience'] },
    { id:'w-amberr', cat:'identity', tag:'Brand Identity', title:'Amberr Skincare Identity', initials:'AM', accent:'#FFB35C', tagBg:'rgba(255,140,0,0.15)', grad:'linear-gradient(135deg,#1F1508,#332512)', weeks:'5 weeks', loc:'Bengaluru, India', video:'', desc:'A warm, botanical identity system for a clean-beauty skincare line - wordmark, amber colour grammar and a modular label system that scales across a growing SKU range. [Placeholder project - swap for a real case study.]', outcomes:['Modular label system across 14 SKUs','Consistent shelf presence in premium retail','Brand kit handed off for in-house rollout'] },
    { id:'w-safal', cat:'digital', tag:'Web Development', title:'Safal Agri Commerce Platform', initials:'SF', accent:'#60A5FA', tagBg:'rgba(0,102,178,0.15)', grad:'linear-gradient(135deg,#08140A,#102A16)', weeks:'7 weeks', loc:'Nagpur, India', video:'', desc:'A lightweight B2B commerce platform connecting farmer collectives to bulk buyers - built for low-bandwidth rural connections with an offline-first catalogue. [Placeholder project - swap for a real case study.]', outcomes:['Offline-first catalogue for low-bandwidth users','Onboarded 40+ farmer collectives at launch','Order flow completed in under 3 taps'] }
  ],

  // Ordered ids of the works featured on the homepage (max 6, in display order).
  // Managed via the CMS "Featured" screen. Falls back to the first 6 works if empty.
  featured: ['w-95','w-wysax','w-ush','w-smw','w-ritz','w-iucn'],

  // ---- CLIENT LOGOS ------------------------------------------------------
  // half:true = wordmark-heavy logo that renders at reduced height.
  logos: [
    { src:'assets/logos/c-3eh.png', name:'3EH' },
    { src:'assets/logos/c-tata-trusts.png', name:'Tata Trusts' },
    { src:'assets/logos/c-amberr.png', name:'Amberr', half:true },
    { src:'assets/logos/c-baidyanath.png', name:'Baidyanath' },
    { src:'assets/logos/c-cini.png', name:'CINI' },
    { src:'assets/logos/c-kavya-k.png', name:"Kavya K", half:true },
    { src:'assets/logos/c-fyp.png', name:'Find Your Passion' },
    { src:'assets/logos/c-fx.png', name:'FX' },
    { src:'assets/logos/c-haldirams.png', name:"Haldiram's" },
    { src:'assets/logos/c-ss1.png', name:'SS1' },
    { src:'assets/logos/c-indian-railway.png', name:'Indian Railways' },
    { src:'assets/logos/c-iucn.png', name:'IUCN' },
    { src:'assets/logos/c-kadambi-group.png', name:'Kadambi Group' },
    { src:'assets/logos/c-kadambi-hr.png', name:'Kadambi HR' },
    { src:'assets/logos/c-kadambi-seva.png', name:'Kadambi Seva' },
    { src:'assets/logos/c-dhara.png', name:'Dhara', half:true },
    { src:'assets/logos/c-cibic.png', name:'CIBIC' },
    { src:'assets/logos/c-berry.png', name:'Berry' },
    { src:'assets/logos/c-lafifa.png', name:'Lafifa' },
    { src:'assets/logos/c-ss4.png', name:'SS4' },
    { src:'assets/logos/c-natural-intelligence.png', name:'Natural Intelligence' },
    { src:'assets/logos/c-nature-monk.png', name:'Nature Monk' },
    { src:'assets/logos/c-idias.png', name:'IDIAS' },
    { src:'assets/logos/c-sol101.png', name:'Sol101' },
    { src:'assets/logos/c-sadhu.png', name:'Sadhu' },
    { src:'assets/logos/c-safal.png', name:'Safal', half:true },
    { src:'assets/logos/c-ada.png', name:'ADA' },
    { src:'assets/logos/c-ss5.png', name:'SS5' },
    { src:'assets/logos/c-ss6.png', name:'SS6' },
    { src:'assets/logos/c-ss7.png', name:'SS7' },
    { src:'assets/logos/c-ss8.png', name:'SS8' },
    { src:'assets/logos/c-ss9.png', name:'SS9' },
    { src:'assets/logos/c-ritz.png', name:'The Ritz London' },
    { src:'assets/logos/c-ush.png', name:'USH Naturals', half:true },
    { src:'assets/logos/c-zs-gemstone.png', name:'ZS Gemstone' }
  ],

  // ---- REVIEWS / TESTIMONIALS -------------------------------------------
  // Works page shows the first 9, then a "load more" reveals the rest.
  reviews: [
    { quote:'"Turtle Labs turned our technical specs into a story that enterprise buyers in the Gulf couldn\'t ignore. Our inbound deal size doubled in 90 days."', name:'DTORR Industrial', loc:'Dubai, UAE', initials:'DT', avBg:'rgba(0,102,178,0.12)', avBorder:'var(--blue)', avFg:'var(--blue)' },
    { quote:'"Our brand went from generic SaaS to an unmistakable market leader in under 60 days. The clarity they brought saved us months of wasted marketing spend."', name:'WYSAX Systems', loc:'Toronto, Canada', initials:'WY', avBg:'rgba(0,168,107,0.12)', avBorder:'var(--greent)', avFg:'var(--greent)' },
    { quote:'"They don\'t just design; they eliminate every piece of fluff until your message is unbreakable. Working with Turtle Labs was our best investment of 2024."', name:'LSP Sustainable Tech', loc:'London, UK', initials:'LS', avBg:'rgba(0,163,224,0.12)', avBorder:'var(--cyan)', avFg:'var(--cyan)' },
    { quote:'"Excellent. I enjoyed working with Turtle Labs - fast, flexible and did a very good job. Collaborative and genuinely committed to quality. I would definitely recommend their services, and I would hire them again."', name:'Michel Paszto \u00b7 The Ritz Hotel', loc:'London, UK \u00b7 Event Collateral Design', initials:'MP', avBg:'rgba(236,48,19,0.12)', avBorder:'var(--red)', avFg:'var(--red)' },
    { quote:'"Turtle Labs handled our branding, product catalogue and event collaterals end to end. The catalogue finally does our range justice, and the identity carried cleanly across every touchpoint. Reliable, sharp, and easy to work with."', name:'ABS Trading', loc:'Dubai, UAE \u00b7 Branding & Catalogue', initials:'AB', avBg:'rgba(0,102,178,0.12)', avBorder:'var(--blue)', avFg:'var(--blue)' },
    { quote:'"For our Leaders Forum in Jeju, Turtle Labs cut a single event film that carried multiple languages in one piece and captured the very best moments of the days. Exactly the coverage the moment deserved."', name:'IUCN', loc:'Jeju \u00b7 Leaders Forum Coverage', initials:'IU', avBg:'rgba(0,168,107,0.12)', avBorder:'var(--greent)', avFg:'var(--greent)' },
    { quote:'"The rebrand gave our specialty coffee the shelf presence we always wanted. The compostable pack and origin-tracing story became talking points with every buyer."', name:'Malabar Reserve', loc:'Singapore \u00b7 Packaging', initials:'MR', avBg:'rgba(255,140,0,0.12)', avBorder:'var(--amber)', avFg:'var(--amber)' },
    { quote:'"We came in with a confusing spec-heavy site and left with a platform that loads instantly and actually converts. Demo bookings jumped in the first two months."', name:'Natural Intelligence', loc:'Bengaluru, India \u00b7 Web', initials:'NI', avBg:'rgba(0,163,224,0.12)', avBorder:'var(--cyan)', avFg:'var(--cyan)' },
    { quote:'"Professional, responsive and genuinely invested in the outcome. Our new identity finally matches the ambition of the company."', name:'Kadambi Group', loc:'Kochi, India \u00b7 Brand Identity', initials:'KG', avBg:'rgba(0,168,107,0.12)', avBorder:'var(--greent)', avFg:'var(--greent)' },
    { quote:'"A calm, capable team that made a complex packaging rollout feel simple. Everything shipped on time and on brand."', name:"Haldiram's", loc:'India \u00b7 Packaging & Print', initials:'HR', avBg:'rgba(200,0,24,0.12)', avBorder:'var(--red)', avFg:'var(--red)' },
    { quote:'"They understood our sustainability mission and translated it into visuals that feel honest, not greenwashed. Rare to find."', name:'Nature Monk', loc:'India \u00b7 Branding', initials:'NM', avBg:'rgba(0,168,107,0.12)', avBorder:'var(--greent)', avFg:'var(--greent)' },
    { quote:'"From strategy to launch, Turtle Labs stayed sharp and dependable. The event film we commissioned still gets shared internally a year on."', name:'CINI', loc:'India \u00b7 Motion & Video', initials:'CI', avBg:'rgba(0,102,178,0.12)', avBorder:'var(--blue)', avFg:'var(--blue)' }
  ],

  // ---- SERVICES ----------------------------------------------------------
  services: [
    { title:'Website development + AI', chips:[['Code','rgba(200,0,24,0.15)','var(--red)'],['Performance','rgba(255,69,0,0.15)','var(--orange)'],['Builds','rgba(255,140,0,0.15)','var(--amber)'],['AI integration','rgba(0,168,107,0.15)','var(--greent)']], desc:'Ultra-light, fast-loading sites and platforms - engineered for sub-second loads and conversion-first journeys, now with AI integration: assistants, smart search and workflow automation built into the build.' },
    { title:'Brand systems', chips:[['Identity','rgba(200,0,24,0.15)','var(--red)'],['Colour','rgba(255,140,0,0.15)','var(--amber)'],['Typography','rgba(0,163,224,0.15)','var(--cyan)']], desc:'Identity, colour grammar and typography systems that survive every touchpoint - from pitch decks to packaging.' },
    { title:'Digital marketing', chips:[['Campaigns','rgba(0,168,107,0.15)','var(--greent)'],['Social','rgba(0,168,107,0.15)','var(--greent)'],['SEO','rgba(0,102,178,0.15)','var(--blue)']], desc:'Full-funnel campaigns, social content systems and search visibility that compounds - built to convert, measured monthly.' },
    { title:'Motion & video', chips:[['Films','rgba(0,102,178,0.15)','var(--blue)'],['Reels','rgba(0,163,224,0.15)','var(--cyan)'],['Animation','rgba(0,163,224,0.15)','var(--cyan)']], desc:'Brand films, product reels and motion systems that tell your story in seconds - cinematic where it counts, light where it loads.' },
    { title:'Packaging & print', chips:[['Structural','rgba(255,140,0,0.15)','var(--amber)'],['Covers','rgba(200,0,24,0.15)','var(--red)'],['Sustainable','rgba(0,168,107,0.15)','var(--greent)']], desc:'Zero-waste structural packaging and print collateral with sustainability embedded in the story, not stapled on.' },
    { title:'Editorial design', chips:[['Print','rgba(255,69,0,0.15)','var(--orange)'],['Layouts','rgba(255,140,0,0.15)','var(--amber)'],['Publications','rgba(0,102,178,0.15)','var(--blue)']], desc:'Reports, catalogues and publications with editorial-grade layout systems - designed to be read, kept and shared.' }
  ],

  // ---- SECTORS -----------------------------------------------------------
  sectors: ['Ayurvedic Wellness','Metro & Transit Infrastructure','Renewable Energy','B2B Enterprise SaaS','Specialty Organic Coffee','Sustainable Cold-Chain Logistics','Gulf Market Retail','Artisan Handloom & Craft','Circular Packaging Systems','Fintech for SMBs'],

  // ---- STATS / THE NUMBERS SO FAR ---------------------------------------
  stats: [
    { value:'184', label:'Brands Scored', color:'var(--greent)' },
    { value:'+34%', label:'Average Score Lift', color:'var(--blue)' },
    { value:'5', label:'Countries Served (UAE, AU, EU, SG, IN)', color:'var(--red)' },
    { value:'0.06g', label:'CO2 / Page View (Live Calculated)', color:'var(--cyan)' }
  ],

  // ---- JOURNAL / ARTICLES -----------------------------------------------
  // category + industry drive the Journal-page tabs. body = full article.
  journalCategories: ['Branding','Strategy','Web & Tech','Sustainability','Process'],
  journalIndustries: ['Wellness','Retail','Transit','SaaS','Food & Bev','Nonprofit'],
  journal: [
    { id:'j-logo', category:'Strategy', industry:'Retail', tag:'Positioning', tagBg:'rgba(255,69,0,0.15)', tagFg:'var(--orange)', grad:"url('assets/journal/logo-thumb.png') center/cover no-repeat, var(--card)", date:'Aug 25, 2026', readTime:'9 min read', author:'Aditya, Founder', title:"Why your logo isn't the problem", excerpt:'When growth stalls, the first instinct is to redesign the logo. The data says the logo buys you a few seconds - and something else entirely decides whether the customer stays.', body:[
      'Every founder has had this moment. Growth stalls, a big client goes quiet, a review reads harsher than it should, and the first instinct is to open Canva and start looking at fonts. Somewhere along the way, "our brand isn\u2019t working" got translated into "our logo isn\u2019t working," and a genuine business problem turned into a design brief.',
      'Here is the uncomfortable part. The data says the logo is rarely where the actual damage happens. It says something more specific: your visual identity buys you the first few seconds, and then something else entirely decides whether the customer stays.',
      'The part that\u2019s true: visuals do open the door. This is not an argument against design. The research on first impressions is clear and worth taking seriously.',
      'The US Small Business Administration found that 75% of people judge a company\u2019s credibility based on the design of its website alone, before they read a word of copy or a single review. Separate research on visual trust found that 92% of people consider a well-designed website more trustworthy, and 94% say they are more likely to stay on a site with an attractive layout. On top of that, a single logo exposure is enough for 63% of consumers to recognize it again later, which is the entire point of having one.',
      'So the visual layer is doing real work. It sets the first impression, and first impressions form in milliseconds, long before a customer has any other information to go on. If your logo genuinely looks like it was made in a hurry in 2013, that is worth fixing. It is not nothing.',
      'But here is what the data says next, and it is the part most founders skip past on the way to the redesign brief.',
      'The part that\u2019s actually breaking: everything after the first impression. Once a customer has clicked through, the visuals have basically finished their job. What happens next is where the real erosion occurs, and it is not subtle.',
      'PwC\u2019s 2025 Customer Experience Survey found that 52% of consumers say they have stopped buying from a brand entirely because of a bad experience with its product or service, and another 29% stopped specifically because of a poor customer experience, online or in person. That is not a logo problem. That is a promise problem.',
      'Forrester\u2019s research puts a number on just how wide this gap is: only 10% of customers say brands actually meet their expectations for a good experience. Ninety percent are being let down somewhere between what the brand promised and what it delivered, and no amount of a cleaner wordmark closes that gap.',
      'Here is the part that should really worry you. HubSpot\u2019s research found that 91% of unhappy customers never complain. They just leave. There is no angry email, no one-star review flagging the exact problem, no support ticket you can point to and fix. The business simply gets quieter, the founder assumes it is a marketing visibility issue, and the actual cause, a broken promise nobody surfaced, never gets diagnosed.',
      'And the damage compounds in a specific, measurable way. Research from Ruby Newell-Legner found it takes roughly 12 positive experiences to make up for a single unresolved negative one. American Express\u2019s research found that 13% of dissatisfied customers tell 15 or more people about the bad experience. Meanwhile Salesforce\u2019s research shows that 73% of customers say a good experience with one company raises their expectations for every other company they deal with, meaning your competitors are training your customers to expect more from you, whether you\u2019ve kept up or not.',
      'None of this shows up as "the logo looks dated." It shows up as slower growth, quieter churn, and a nagging sense that something is off that a rebrand mysteriously never fixes.',
      'Why the logo gets blamed anyway. There is a simple reason founders reach for the visual fix first. It is the only layer of the brand you can actually see and act on in an afternoon. You cannot open a file and quickly redesign "our support response time" or "the gap between what our ads promise and what our onboarding delivers." You can absolutely open a file and try a new logo. It feels like progress because it is visible, contained, and finishable by Friday.',
      'But look back at the brand strategy pyramid: purpose, vision, mission, values, positioning, and only then, at the very top, identity, meaning the logo, the colors, the fonts. Identity is the last layer, not the first. It is supposed to express the five layers underneath it. A new logo on top of an unclear positioning and an inconsistent customer experience is not a brand fix. It is a paint job on a foundation nobody has checked.',
      'How to actually tell the difference. Before you brief a logo redesign, run this check instead.',
      'Pull up your last 20 customer conversations, support tickets, or reviews. Are people commenting on how the brand looks, or are they describing a gap between what they expected and what they got? Slow replies, a product that didn\u2019t match the description, a price that felt different from what was promised. That second category is a delivery and positioning problem, not a visual one, and it is usually where the real revenue is leaking.',
      'Ask your team, honestly, whether the brand consistently delivers on what your marketing promises. If the answer involves any hesitation, that hesitation is costing you more than an outdated logo ever will.',
      'Check whether your positioning statement is specific enough that a customer could tell you apart from your three closest competitors without seeing your logo at all. If they couldn\u2019t, that is the actual gap, and it sits several layers below identity on the pyramid.',
      'The honest fix. If your visuals are genuinely dated, fix them. It is real, it is worth doing, and the first-impression data above is not made up. But do it as the last step of a brand strategy exercise, not the first move you make when something feels off. A logo redesign on top of unclear positioning and an inconsistent customer experience just gives the same underlying problem a nicer coat of paint, and the 90% of customers whose expectations still aren\u2019t being met will notice within the first week.',
      'If you want to find out whether it\u2019s actually your identity or something underneath it, that diagnosis is exactly what the Brand Strategy Workbook is built to walk you through. Download it free at turtlelabs.co.in, start with the foundation chapters before you touch the identity ones, and if you want a second, trained set of eyes on where your specific gap actually is, book a 30-minute call.',
      'Sources: US Small Business Administration website credibility research; Cutting Edge PR visual trust research; Web Tonic e-commerce branding research (ZipDo logo recognition data); PwC 2025 Customer Experience Survey; Forrester customer experience benchmarks; HubSpot customer complaint research; Ruby Newell-Legner customer service research; American Express global customer service barometer; Salesforce State of the Connected Customer research.'
    ] },
    { id:'j-position', category:'Strategy', industry:'Retail', tag:'Positioning', tagBg:'rgba(255,69,0,0.15)', tagFg:'var(--orange)', grad:"url('assets/journal/position-thumb.png') center/cover no-repeat, var(--card)", date:'Aug 24, 2026', readTime:'8 min read', author:'Aditya, Founder', title:'"Sustainable" is not a position, it is a word', excerpt:'Say "sustainable" ten times and it stops meaning anything - which is roughly what the market has done to it. If your strategy stops at the label, you do not have a position. You have an adjective.', body:[
      'Say the word "sustainable" out loud ten times and it stops meaning anything. That is not a joke, it is roughly what has happened to the word in the market. It sits on shampoo bottles, insurance ads, real estate brochures, and airline seatback cards. It has been used so often, by so many people, for so many different things, that it has become wallpaper. Customers see it and their brain does not react. Worse, for a growing number of them, it triggers suspicion instead of trust.',
      'If your brand strategy stops at the label "we are sustainable," you do not have a position. You have an adjective. And adjectives do not win markets anymore.',
      'The trust collapse, in numbers. This is not a vibe. It is measurable, and the numbers have moved fast.',
      'Sustainable Jungle\u2019s consumer research tracked greenwashing concern rising from 8% of consumers in 2022 to 43% in 2025, more than a fivefold increase in three years, making it one of the top two barriers to buying from a sustainability-positioned brand, second only to price. That is not a slow drift. That is a market losing patience in real time.',
      'The scrutiny is earned. A KPMG survey found that 76% of consumers consider false or misleading sustainability claims to be the clearest form of greenwashing they encounter, and over half of respondents globally say they have personally seen or heard misleading information about a brand\u2019s environmental actions. On the corporate side, roughly 68% of US executives have openly acknowledged that their own companies engage in greenwashing. That is not activists making an accusation. That is the people writing the claims admitting the claims do not hold up.',
      'Regulators are reaching the same conclusion. An EU Commission coordinated review found that more than half of environmental claims made across the bloc were vague, exaggerated, or unfounded, and 40% came with no supporting evidence at all. That is why the EU is now moving toward laws that ban unsubstantiated green claims outright, and why France can already fine misleading environmental advertising up to 300,000 euros or 80% of the campaign\u2019s cost.',
      'And here is the part that should worry every brand owner, not just the ones cutting corners: NielsenIQ found that 77% of global consumers say they would stop buying from a company altogether if it were found guilty of greenwashing. Once a customer stops trusting environmental claims in general, they stop bothering to look for the honest ones too. The bad actors are not just damaging their own brand. They are burning the credibility of the entire category, including yours.',
      'Why the word fails as a position. A brand position answers one question precisely: why should this specific customer choose you over the specific alternative they would otherwise pick. "Sustainable" answers none of that. It does not say what problem you solve, for whom, or what you actually do differently. It is a claim with the proof surgically removed.',
      'Compare these two statements. "We are a sustainable clothing brand." Versus: "Every t-shirt we make uses 71% less water than conventional cotton production, verified by GOTS certification, because our factory partners in Tamil Nadu switched to closed-loop dyeing in 2023."',
      'The first sentence could belong to literally any apparel company on earth, including the ones currently under investigation for exactly this kind of claim. The second could only belong to one company, because it contains specifics that can be checked, a number that can be audited, a certification that can be verified, and a story that explains why the number is true. One is marketing. The other is a position.',
      'This is the exact gap regulators are now closing by law, and the exact gap customers are already closing with their wallets. Roughly 60% of fashion brands\u2019 sustainability claims have been found unsubstantiated or misleading in recent industry reviews, which means the brands that can actually back their claims with evidence are sitting on a genuine, defensible advantage - if they are willing to say the specific thing instead of the comfortable thing.',
      'What an actual position looks like. Real environmental positioning is built the same way any strong position is built, using specifics instead of adjectives.',
      'Name the exact practice, not the category. Not "eco-friendly," but "packaging made from 100% post-consumer recycled cardboard, sourced within 200 kilometers of our warehouse." A customer cannot verify "eco-friendly." A customer can verify a supplier, a percentage, and a distance.',
      'Attach a number that can be checked. Water saved, carbon avoided, waste diverted, percentage recycled. If the number cannot be independently audited or traced to a named methodology, it is not a proof point, it is a guess dressed up as one.',
      'Name the certification or the source, not just the claim. GOTS, Fair Trade, B Corp, a named third-party audit. Certifications exist precisely because "trust us" stopped being enough. A claim with no certifying body behind it now reads to a skeptical customer as a claim with something to hide.',
      'Say what you are not doing, and why that costs you something. A real position usually involves a real tradeoff. "We do not use virgin plastic, which means our unit costs are higher and our packaging looks less polished on a shelf, and we have decided that tradeoff is worth it." A position with no cost attached to it is not a decision, it is a slogan.',
      'Tell the specific story behind the specific number. Not "we care about the planet," but the actual decision, the actual year it changed, the actual factory or process involved. Specificity is what separates a claim a lawyer would flag from a claim a customer would repeat to a friend.',
      'The honest test. Before you put the word "sustainable" on anything again, run this test. Read your own claim back and ask: could my three biggest competitors say this exact sentence about themselves without changing a single word. If the answer is yes, you have not built a position. You have borrowed a word everyone else is also borrowing, at the exact moment that word is losing its meaning fastest.',
      'The brands that will win the next decade of this conversation are not the ones that say "sustainable" the loudest. They are the ones specific enough, and honest enough about the tradeoffs, that saying nothing at all would actually cost them the trust they have built.',
      'If you want help turning a vague sustainability claim into a position that survives scrutiny, that is exactly the kind of positioning work we do at Turtle Labs. Download the free Brand Strategy Workbook to start mapping your own positioning, or if you already know your current claim will not survive the test above, book a 30-minute call and let\u2019s fix it properly.',
      'Sources: Sustainable Jungle Consumer Report (2025 to 2026); KPMG UK Greenwashing Survey; NielsenIQ Global Consumer Research; Zippia Greenwashing Statistics (2026); European Commission coordinated review of environmental claims; industry reviews of fashion sector sustainability claims.'
    ] },
    { id:'j-workbook', category:'Strategy', industry:'SaaS', tag:'Strategy', tagBg:'rgba(0,102,178,0.15)', tagFg:'var(--blue)', grad:"url('assets/journal/workbook-thumb.jpg') center/cover no-repeat, var(--card)", date:'Aug 20, 2026', readTime:'7 min read', author:'Aditya, Founder', title:'Why we built a workbook instead of another free PDF', excerpt:'Most free brand guides are built to generate leads, not clarity. So we built something you would actually finish - six chapters, five worksheets and ten ready-to-run AI prompts, all free.', body:[
      'There are roughly 40 million "Ultimate Brand Guide" PDFs sitting unread in downloads folders right now. Okay, we made that number up. But you know the feeling - you trade your email for a lead magnet, open it once, skim the cover page, and never touch it again. Ninety seconds of relevance, then it is dead weight in a folder called "Marketing Stuff (2023)."',
      'We did not want to make one more of those.',
      'The problem with free PDFs. Most "free brand strategy guides" are built to generate leads, not clarity. They are 12 slides of inspiration porn - nice quotes, a few frameworks, a CTA at the end. You read them. You feel briefly smart. Nothing changes.',
      'Here is the uncomfortable part: the research backs this up. Lucidpress\u2019s State of Brand Consistency studies, one of the most cited pieces of research in this space, surveying 400+ brand management professionals, found that 95% of companies have brand guidelines, but only around 25 to 30% of them actually enforce those guidelines consistently. A document sitting in a Google Drive folder does not build a brand. Nobody opens it during crunch week. Nobody checks the new intern\u2019s Instagram caption against it.',
      'That gap between "having guidelines" and "using guidelines" is where most brands quietly leak value.',
      'And the value is real, not theoretical. Multiple Lucidpress/Marq studies, tracking brand performance across hundreds of companies, put the revenue impact of consistent branding somewhere between 10% and 33%, with about two-thirds of respondents crediting consistency for double-digit revenue growth. For a business doing \u20b94 crore a year, that is not a rounding error. That is the difference between a good year and a breakout one.',
      'So the issue was never "does brand strategy matter." Everyone nods at that. The issue is that nobody finishes the document that is supposed to make it real.',
      'So we built something you would actually finish. The Turtle Labs Brand Strategy Workbook is not a guide you read. It is a workbook you fill in - six chapters, five worksheets, and a chapter of ten ready-to-run AI prompts, built around one blueprint: Purpose to Vision to Mission to Values to Positioning to Identity.',
      'Every worksheet forces a decision instead of an observation. Not "here is what positioning is" but "write your positioning statement, right now, in this box." Not "know your customer" but "name your persona, list their top 3 frustrations, write the one-paragraph summary." By the time you close the last page, you do not have inspiration. You have a foundation document you can actually hand to a designer, a copywriter, or your future self in six months.',
      'And because we know brand strategy work rarely survives contact with an AI blank page, we built the tenth chapter specifically for that moment - ten prompts, ready to paste into Claude or ChatGPT, that turn your filled-in worksheets into positioning statements, taglines, homepage copy, and content pillars. No prompt engineering required. Just fill in the brackets.',
      'Here is the honest part. The full workbook - every chapter, every worksheet, all ten AI prompts - is completely free. Not free-with-an-asterisk. Not "free" until page 4 where it asks for a credit card. You can download it, fill it out with your own business details, run it through the AI prompts yourself, and walk away with a real brand foundation. No call required, no email drip campaign, no upsell hiding in the footer.',
      'What we do charge for is what a template can never do: a second set of trained eyes on your specific business, catching the blind spots you cannot see because you are standing too close to your own brand. If you fill out the workbook and want a detailed analysis - someone to pressure-test your positioning, map your actual competitive landscape, or turn the worksheet into a brand system with identity and design - that is a paid engagement. That is fair. Fifteen years of doing this for brands like Nagpur Metro, NASSCOM, and Godrej is not something we are going to pretend fits inside a free template.',
      'We think that is a more honest trade than most of what is out there: a genuinely useful free tool that respects your time, and a clearly separate paid option for people who want a professional to actually build with them, not a "free scorecard" designed to make you feel incomplete until you pay.',
      'The math on doing this yourself vs. not doing it at all. Remember that 81% of companies struggle with off-brand content even when guidelines exist. The difference between them and the 20% who do not is not better guidelines - it is that someone actually filled the thing in, argued over the wording, and made it specific enough to be useless for anyone else\u2019s business. A positioning statement you cannot tell apart from your competitor\u2019s is not a positioning statement. It is furniture.',
      'So if you are a founder, a marketing lead, or a solo operator staring down a rebrand, a pivot, or just the nagging sense that your messaging is "fine but forgettable" - this workbook is built for the two hours you are willing to give it, not the two months you keep meaning to give it.',
      'What to do next. First, download the free workbook - every chapter, every worksheet, all 10 AI prompts, no strings. Second, fill it in with your real business details; be specific, because vague answers produce vague brands. Third, run the AI prompts to turn your answers into positioning statements, taglines, and homepage copy. Fourth, if you want a professional to go deeper - audit your positioning, map your competitors properly, or build out your full brand system - book a 30-minute call. That is the only part we charge for.',
      'The clearest brands win. We would rather you get clear for free than stay confused because a PDF gated the truth behind a form.',
      'Sources: Lucidpress/Marq State of Brand Consistency Reports (2016, 2019, 2021); Demand Metric.'
    ] },
    { id:'j-accessibility', category:'Web & Tech', industry:'Nonprofit', tag:'Accessibility', tagBg:'rgba(0,168,107,0.15)', tagFg:'var(--greent)', grad:'linear-gradient(135deg, rgba(0,168,107,0.32), rgba(0,0,0,0) 65%), var(--card)', date:'Jun 28, 2026', readTime:'5 min read', author:'Turtle Labs', title:'Accessibility is not an afterthought - it is a feature', excerpt:'Designing for everyone is not a compliance checkbox. It is one of the highest-leverage quality signals your brand can send.', body:[
      'Accessibility gets framed as a legal obligation, which is exactly why it is so often bolted on at the end. Reframed as a feature, it changes how you design from the first sketch.',
      'Good contrast, clear focus states and readable type do not just help users with disabilities - they make the product better for everyone, on every screen, in every lighting condition.',
      'The teams that do this well treat it as craft, not compliance. They test with a keyboard, they check colour contrast as they design, and they write alt text like it matters - because it does.',
      'The reward is trust. A brand that is effortless to use for everyone reads as competent and considerate, and that impression carries into everything else you do.'
    ] },
    { id:'j-contrast', category:'Branding', industry:'Retail', tag:'Branding', tagBg:'rgba(255,69,0,0.15)', tagFg:'var(--orange)', grad:'linear-gradient(135deg, rgba(255,69,0,0.32), rgba(0,0,0,0) 65%), var(--card)', date:'Jun 3, 2026', readTime:'4 min read', author:'Turtle Labs', title:'How visual contrast shapes the way people trust brands', excerpt:'Contrast is not just an accessibility metric. It is a signal of confidence - and confidence is what buyers read as trust.', body:[
      'When a brand hedges - muddy colours, timid type, everything the same weight - people feel the hesitation even if they cannot name it. Contrast is how a brand shows it knows what matters.',
      'A single decisive accent against a calm ground draws the eye exactly where you want it. Spread that accent everywhere and it stops meaning anything.',
      'Hierarchy is contrast applied to information. The most important thing should look the most important. It sounds obvious, and it is the thing most sites get wrong.',
      'Used well, contrast makes a small brand look sure of itself - and sureness is the cheapest trust signal you can buy.'
    ] },
    { id:'j-carbon', category:'Sustainability', industry:'SaaS', tag:'Sustainability', tagBg:'rgba(0,168,107,0.15)', tagFg:'var(--greent)', grad:'linear-gradient(135deg, rgba(0,168,107,0.3), rgba(0,0,0,0) 65%), var(--card)', date:'May 19, 2026', readTime:'7 min read', author:'Turtle Labs', title:'The carbon cost of a heavy website - and what to do about it', excerpt:'Every megabyte you ship is energy someone else has to spend. Lightweight is not just faster - it is more sustainable.', body:[
      'The average web page has quietly ballooned over the last decade. Most of that weight is invisible to the people who commission it and expensive for the people who load it.',
      'A lighter site loads faster, ranks better and costs less to run - and it also burns less energy across every device that opens it. Sustainability and performance are the same project.',
      'The biggest wins are boring: right-size your images, drop the fonts you are not using, and question every third-party script. Most heavy sites are heavy by accident, not by need.',
      'We build to a payload budget the same way we build to a deadline. When weight is a first-class constraint, the whole product gets sharper.'
    ] },
    { id:'j-naming', category:'Strategy', industry:'Food & Bev', tag:'Strategy', tagBg:'rgba(0,102,178,0.15)', tagFg:'var(--blue)', grad:'linear-gradient(135deg, rgba(0,102,178,0.3), rgba(0,0,0,0) 65%), var(--card)', date:'May 2, 2026', readTime:'5 min read', author:'Turtle Labs', title:'Naming a brand people actually remember', excerpt:'The best names are not the cleverest. They are the ones that survive being said out loud, misheard and typed with one thumb.', body:[
      'Naming turns into a thesaurus exercise far too quickly. The real test is not what a name means - it is how it behaves in the wild.',
      'Say it on a phone call. Type it on a phone. Read it at the top of a slide from the back of a room. A great name survives all three without a spelling explanation.',
      'Distinctiveness beats description. You do not need the name to explain the business; you need it to be ownable and easy to remember once someone learns what you do.',
      'Leave room to grow. The name that perfectly describes your first product is the one you resent in three years when you launch your second.'
    ] },
    { id:'j-transit', category:'Branding', industry:'Transit', tag:'Branding', tagBg:'rgba(255,69,0,0.15)', tagFg:'var(--orange)', grad:'linear-gradient(135deg, rgba(255,140,0,0.3), rgba(0,0,0,0) 65%), var(--card)', date:'Apr 15, 2026', readTime:'6 min read', author:'Turtle Labs', title:'What metro wayfinding taught us about clarity', excerpt:'Transit systems have to be understood by a stranger, in a hurry, in a second language. Every brand could learn from that constraint.', body:[
      'A metro map is a brand working under the harshest possible conditions: a stressed stranger, moving fast, who cannot afford to misread it. That pressure produces remarkable clarity.',
      'The lesson is subtraction. Great wayfinding shows you only what you need at the moment you need it, and hides everything else until later.',
      'Colour does heavy lifting, but only because it is used with discipline - one meaning per colour, held consistently across the whole system.',
      'Most marketing sites would be transformed by asking a single transit question: what does this person need to know right now, and what can wait?'
    ] },
    { id:'j-proof', category:'Strategy', industry:'Retail', tag:'Strategy', tagBg:'rgba(0,102,178,0.15)', tagFg:'var(--blue)', grad:'linear-gradient(135deg, rgba(0,163,224,0.3), rgba(0,0,0,0) 65%), var(--card)', date:'Mar 30, 2026', readTime:'4 min read', author:'Turtle Labs', title:'Social proof that actually persuades', excerpt:'Logos and star ratings are table stakes. The proof that moves buyers is specific, recent and told by someone like them.', body:[
      'A wall of client logos reassures nobody on its own. It answers "are you real?" but not the question a buyer is actually asking: "will this work for me?"',
      'Specificity is what persuades. A number, a timeframe and a named outcome beat ten glowing but vague endorsements every time.',
      'Relevance beats prestige. A buyer trusts a review from a company that looks like theirs more than a famous logo from a different world.',
      'Place proof where the doubt is. The best testimonial is the one that appears exactly at the moment a visitor starts to hesitate.'
    ] },
    { id:'j-motion', category:'Process', industry:'Nonprofit', tag:'Process', tagBg:'rgba(0,163,224,0.15)', tagFg:'var(--cyan)', grad:'linear-gradient(135deg, rgba(103,232,249,0.28), rgba(0,0,0,0) 65%), var(--card)', date:'Mar 8, 2026', readTime:'5 min read', author:'Turtle Labs', title:'Cutting a day-long event into a film people finish', excerpt:'The hardest part of event coverage is not the shooting. It is deciding what to leave out.', body:[
      'A full-day forum can yield hours of footage and a single truth: almost none of it belongs in the final cut. Editing is the job.',
      'We start from the message, not the timeline. What is the one thing this event should make a viewer feel or do? Everything that does not serve that is a candidate for the floor.',
      'Pace is mercy. A highlights film respects the viewer\'s time, and a film people actually finish is worth more than a complete record nobody watches.',
      'Multiple languages, one cut. Designing the edit to carry more than one audience from the start beats producing five separate versions later.'
    ] },
    { id:'j-packaging', category:'Sustainability', industry:'Food & Bev', tag:'Sustainability', tagBg:'rgba(0,168,107,0.15)', tagFg:'var(--greent)', grad:'linear-gradient(135deg, rgba(74,222,128,0.28), rgba(0,0,0,0) 65%), var(--card)', date:'Feb 20, 2026', readTime:'6 min read', author:'Turtle Labs', title:'Sustainable packaging without the greenwash', excerpt:'Shoppers can smell a hollow eco-claim. Honest sustainability is a design decision, not a sticker.', body:[
      'Slapping a leaf icon and the word "eco" on a pack is not sustainability - it is decoration, and increasingly, shoppers know the difference.',
      'Real sustainability shows up in the structure: less material, mono-materials that actually recycle, and finishes that do not sabotage the recycling stream.',
      'Tell the true story, specifically. "100% compostable pouch" with a QR code to the origin farm beats a vague promise every time.',
      'Done honestly, sustainability becomes a feature buyers choose, not a claim they discount. That is the whole point.'
    ] }
  ]
};
